//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Stock_Automation.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Urunler()
        {
            this.tbl_Satislar = new HashSet<tbl_Satislar>();
        }
    
        public int urunID { get; set; }
        public string urunAd { get; set; }
        public string urunMarka { get; set; }
        public Nullable<short> urunKategori { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<byte> urunStok { get; set; }
    
        public virtual tbl_Kategoriler tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Satislar> tbl_Satislar { get; set; }
    }
}
