//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Stock_Automation.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Satislar
    {
        public int satisID { get; set; }
        public Nullable<int> satisUrun { get; set; }
        public Nullable<int> satisMusteri { get; set; }
        public Nullable<byte> satisAdet { get; set; }
        public Nullable<decimal> satisFiyat { get; set; }
    
        public virtual tbl_Musteriler tbl_Musteriler { get; set; }
        public virtual tbl_Urunler tbl_Urunler { get; set; }
    }
}
